### PR TITLE
Improvements after building a concrete implementation

### PR DESCRIPTION
**Pull request by kevinenax**
I recently created a Datadog tracer in swift and used this repo as the basis. I made a few changes that I think made it easier to implement and I don't think goes against the spec.

The primary change was using `Codable` instead of `Any` for some of the protocols since in the end I think they will have to be casted to be serialized or deserialized anyway.

Other changes made were removing some of the project files that weren't necessary for my flow and that were made before I knew if I was going to be doing a pull request, so those are certainly debatable. But in the end it supports Swift Package Manager still, which is becoming more the norm in Swift libraries anyway.

### CODE REVIEW

**Comment by ryanrhee** [comment]
- I try to avoid checking in Xcode project files. Is this something you feel strongly about?
- Why make the date required for finish? If not passed in, shouldn’t the span finish with the current date time?
- using codable instead of any is fine with me.

**Comment by kevinenax** [comment]
1. None are checked in, the change is actually adding xcodeproj files/folders to the gitignore :)
2. It's been a bit since I made this change, but I also changed the extension to finish at the current date, so the functionality remains the same while removing the need for date to be optional.

**Comment by ryanrhee** [comment]
> finish at the current date

ah yeah i see that. so i think the reason why i made chose to pass a `nil` instead of the current date is that a lot of bigger apps will choose to use their own ntp clocks rather than the system clock but still want the ergonomics of being able to finish a span without specifying the time.

On the other hand, adding a clock interface to the opentracing interfaces seemed very heavy handed.

If you can think of a way to keep the time being required while also accommodating users who want to use ntp clocks, want the ergonomics of `finish()`, and without adding a clock interface, we can certainly make that change.

---

You removed quite a few files related to the toolchain (e.g. python script to choose a simulator, makefile, etc.) - can you explain what the new process would be for building this, releasing this, including it in an xcode project, etc?

**Comment by kevinenax** [comment]
Since the `finish()` is in a protocol extension any implementer can re-implement it in whatever conforms to that protocol and that version will be used instead.

On the other misc files... I had removed them before I planned on doing a pull request, but I'll re-introduce some of them at least.

What I think makes sense is to change the make file to use `swift build` instead of `xcodebuild` so that its platform agnostic.  Which would mean dropping at least the use of the python script if not leaving the script out completely. I also wonder if we shouldn't either drop cocoapods support or add carthage to be more consistent. Thoughts?

**Comment by ryanrhee** [comment]
Great, we can keep `Date` non-optional, and let's add carthage support?

**Comment by ryanrhee** [comment]
If you want to break out the swift logic changes so we can land that now you can do that too. I don't want to remove the existing build stuff- especially the podspecs- without adding carthage support.

**Comment by kevinenax** [comment]
I was thinking the same, I'll split the PR.

**Comment by ryanrhee** [comment]
Thanks!

**Comment by ryanrhee** [comment]
Released in `v0.1.0`

**Pull request merged**
